javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
cd CHAPTER1
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack.java
java Blackjack.java
java Blackjack.java
java Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
cd CHAPTER1
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
javac print.java
java print
javac print.java
javac print.java
java print
java Blackjack
javac Blackjack.java
java Blackjack
h
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
java Blackjack
java Blackjack
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
java Blackjack
java Blackjack
java Blackjack
java Blackjack
cd ..
git add.
git add .
git commit -m .
git push origin master
cd CHAPTER1
javac Blackjack.java
java Blackjack
javac Blackjack.java
javac Blackjack.java
javac Blackjack.java
java Blackjack
java Blackjack
git add .
git commit -m .
git push origin master
git push origin master
cd ..
git add .
git commit -m
git commit -m .
git push origin master
cd CHAPTER1
java Blackjack
java Blackjack
java Blackjack
java Blackjack
java Blackjack
java Blackjack
cd ..
git add .
cd CHAPTER1
java Blackjack
java Blackjack
javac Blackjack.java
java Blackjack
java Blackjack
java PigDice
javac PigDice.javac
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
java PigDice
javac ThereAndBackAgain
touch ThereAndBackAgain.java
javac ThereAndBackAgain.java
javac ThereAndBackAgain.java
java ThereAndBackAgain
touch OverlyComplexFlag.java
javac Blackjack.java
cd CHAPTER1
javac OverlyComplexFlag.java
javac OverlyComplexFlag.java
javac OverlyComplexFlag.java
javac OverlyComplexFlag.java
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag
javac OverlyComplexFlag.java
javac OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
javac OverlyComplexFlag.java
java OverlyComplexFlag
cd ..
git add .
git commit -m .
git push origin master
cd CHAPTER1
java Blackjack
java OverlyComplexFlag
cd ..
git add .
git commit -m .
git push origin master
cd CHAPTER1
cd ..
cd CHAPTER1
javac Blackjack.java
cd ..
git add .
git commit =m
git commit =m .
git add .
git commit -m .
