java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
f
f
cd CHAPTER1
javac ThreeCardMonte.java
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
cd CHAPTER1
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
git add .
git commit -m .
cd ..
git pull https://github.com/asamn/javathehardway master
git push -u origin master
git add .
git commit -m .
git pull https://github.com/asamn/javathehardway master
git push -u origin master
cd CHAPTER1
javac ThreeCardMonte.java
cd ..
git add .
git commit -m .
git pull https://github.com/asamn/javathehardway master
git push -u origin master
cd CHAPTER1
cd CHAPTER1
touch EnterPIN.java
javac EnterPIN.java
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
javac EnterPIN.java
javac EnterPIN.java
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
touch HighLow.java
javac HighLow.java
javac HighLow.java
javac HighLow.java
java HighLow
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
java HighLow
java HighLow
java HighLow
javac HighLow.java
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
java HighLow
java HighLow
java HighLow
javac HighLow.java
cd CHAPTER1
javac HighLow.java
java HighLow
java HighLow
cd ..
git add .
git commit -m .
git push origin master
cd CHAPTER1
java HighLow
touch KeepGuessing.java
javac KeepGuessing
javac KeepGuessing.java
javac KeepGuessing.java
javac KeepGuessing.java
javac KeepGuessing
javac KeepGuessing
java KeepGuessing
java KeepGuessing
touch SafeSquareRoot.java
javac SafeSqaureRoot.java
javac SafeSquareRoot.java
java SafeSquareRoot
java SafeSquareRoot
javac SafeSquareRoot.java
javac SafeSquareRoot.java
java SafeSquareRoot
java SafeSquareRoot
java SafeSquareRoot
javac SafeSquareRoot.java
java SafeSquareRoot
java SafeSquareRoot
java SafeSquareRoot
touch CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
java CoinFlip
java CoinFlip
java CoinFlip
java CoinFlip
java CoinFlip
java CoinFlip
javac CoinFlip.java
java CoinFlip
java CoinFlip
javac CoinFlip.java
java CoinFlip
java CoinFlip
java CoinFlip
java CoinFlip
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
javac CoinFlip.java
java CoinFlip
java CoinFlip
javac CoinFlip.java
java CoinFlip
java CoinFlip
javac CoinFlip.java
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
javac CoinFlip.java
java CoinFlip
java CoinFlip
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
javac CoinFlip.java
java CoinFlip
java CoinFlip
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
java CoinFlip
javac CoinFlip.java
java CoinFlip
java CoinFlip
touch RunningTotal.java
javac RunningTotal.java
javac RunningTotal.java
java RunningTotal
javac RunningTotal.java
cd CHAPTER1
javac RunningTotal.java
javac RunningTotal.java
java RunningTotal
javac RunningTotal.java
java RunningTotal
java RunningTotal
javac RunningTotal.java
java RunningTotal
java RunningTotal
java RunningTotal
java RunningTotal
java RunningTotal
java RunningTotal
java RunningTotal
javac RunningTotal.java
java RunningTotal
javac RunningTotal.java
javac RunningTotal.java
java RunningTotal
javac RunningTotal.java
java RunningTotal
cd ..
git add .
git commit -m . 
git push origin master
cd CHAPTER1
javac RunningTotal.java
javac RunningTotal.java
java RunningTotal
javac RunningTotal.java
java RunningTotal
javac RunningTotal.java
cd CHAPTER1
touch PigDiceComputer.java
javac PigDiceComputer.java
javac PigDiceComputer.java
javac PigDiceComputer.java
javac PigDiceComputer.java
java PigDiceComputer
javac PigDiceComputer.java
javac PigDiceComputer.java
javac PigDiceComputer.java
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
javac PigDiceComputer.java
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
java PigDiceComputer
javac PigDiceComputer.java
javac PigDiceComputer.java
touch PigDice.java
java PigDice.java
javac PigDice.java
javac PigDice.java
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
java PigDice
java PigDice
java PigDice
javac PigDice.java
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
javac PigDice.java
javac PigDice.java
javac PigDice.java
javac PigDice.java
javac PigDice.java
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
n
cd CHAPTER1
javac PigDice.java
java PigDice
java PigDice
javac PigDice.java
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
cd CHAPTER1
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
javac PigDice.java
java PigDice
java PigDice
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
java PigDice
java PigDice
java PigDice
javac PigDice.java
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
java PigDice
javac PigDice.java
java PigDice
javac PigDice.java
java PigDice
cd ..
