touch LittleQuiz.java
javac LitleQuiz.java
javac LittleQuiz.java
javac LittleQuiz.java
java LittleQuiz
java LittleQuiz
java LittleQuiz
javac LittleQuiz.java
javac LittleQuiz.java
javac LittleQuiz.java
java LittleQuiz
javac LittleQuiz.java
java LittleQuiz
javac LittleQuiz.java
java LittleQuiz
javac LittleQuiz.java
java LittleQuiz
javac LittleQuiz.java
java LittleQuiz
java LittleQuiz
javac LittleQuiz.java
java LittleQuiz
javac LittleQuiz.java
java LittleQuiz
java LittleQuiz
javac LittleQuiz.java
java LittleQuiz
git add .
git commit -m .
git commit -m .
git add .
git commit -m .
git push origin master
git pull https://github.com/asamn/javathehardway master
cd ..
git push origin master
git pull https://github.com/asamn/javathehardway master
git add .
git commit -m .
git push origin master
git add .
git commit -m .
git push origin master
touch CollegeAdmission.java
javac CollegeAdmission.java
cd CHAPTER1
javac CollegeAdmission.java
java CollegeAdmission
cd CHAPTER1
touch GenderTitles.java
javac GenderTitles.java
javac GenderTitles.java
javac GenderTitles.java
javac GenderTitles.java
javac GenderTitles.java
java GenderTitles
java GenderTitles
cd CHAPTER1
javac GenderTitles.java
java GenderTitles
javac GenderTitles.java
java GenderTitles
java GenderTitles
java GenderTitles
java GenderTitles
java GenderTitles
java GenderTitles
java GenderTitles
java GenderTitles
cd CHAPTER1
touch ThirtyDays.java
javac ThirtyDays.java
javac ThirtyDays.java
javac ThirtyDays.java
javac ThirtyDays.java
java ThirtyDays
java ThirtyDays
java ThirtyDays
java ThirtyDays
java ThirtyDays
java ThirtyDays
java ThirtyDays
touch DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
java DictionaryOrder.java
javac DictionaryOrder.java
java DictionaryOrder.java
touch RandomNumbers.java
javac RandomNumbers.java
javac RandomNumbers.java
touch RandomNumbers.java
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
cd CHAPTER1
javac RandomNumbers.java
javac RandomNumbers.java
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
javac RandomNumbers.java
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
javac RandomNumbers.java
javac RandomNumbers.java
java RandomNumbers
javac RandomNumbers.java
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
javac  RandomNumbers.java
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
java RandomNumbers
cd CHAPTER1
touch ThreeCardMonte.java
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
javac ThreeCardMonte.java
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
3
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
f
f
cd CHAPTER1
javac ThreeCardMonte.java
javac ThreeCardMonte.java
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
cd CHAPTER1
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
javac ThreeCardMonte.java
java ThreeCardMonte
java ThreeCardMonte
git add .
git commit -m .
cd ..
git pull https://github.com/asamn/javathehardway master
git push -u origin master
git add .
git commit -m .
git pull https://github.com/asamn/javathehardway master
git push -u origin master
cd CHAPTER1
javac ThreeCardMonte.java
cd ..
git add .
git commit -m .
git pull https://github.com/asamn/javathehardway master
git push -u origin master
cd CHAPTER1
cd CHAPTER1
touch EnterPIN.java
javac EnterPIN.java
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
javac EnterPIN.java
javac EnterPIN.java
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
javac EnterPIN.java
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
java EnterPIN
touch HighLow.java
javac HighLow.java
javac HighLow.java
javac HighLow.java
java HighLow
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
java HighLow
java HighLow
java HighLow
javac HighLow.java
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
javac HighLow.java
java HighLow
java HighLow
java HighLow
java HighLow
javac HighLow.java
cd CHAPTER1
javac HighLow.java
java HighLow
java HighLow
cd ..
